FROM node:lts AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the Next.js application
RUN npm run build

# Expose port for the Next.js application
EXPOSE 3000

# Command to run the Next.js application
CMD ["npm", "start"]