# Use the official Node.js image as a base
FROM node:lts AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./frontend/my-app/package.json ./frontend/my-app/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend source code
COPY ./frontend/my-app .

# Build the frontend
RUN npm run build

# Stage 2: Final image
FROM node:lts AS runner

# Set working directory
WORKDIR /app

# Copy the built application from the previous stage
COPY --from=builder /app .

# Expose port 3000 for the Next.js application
EXPOSE 3000

# Serve the application
CMD ["npm", "start"]